<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => '',
    'Advanced Search' => '',
    'Advert' => '',
    'AdvertAddress' => '',
    'AdvertPrice' => '',
    'Advertid' => '',
    'Adverts' => '@@@@',
    'Any' => '',
    'Are you sure you want to delete this item?' => '',
    'Avatar' => '',
    'Cancel' => '',
    'City' => '',
    'Contact' => '',
    'Create' => '',
    'Create Advert' => '@@@@',
    'Create Subject' => '',
    'Delete' => '',
    'Description' => '',
    'Edit' => '',
    'Experience' => '',
    'First Name' => '',
    'For Tutors' => '',
    'Goal' => '',
    'Goals' => '',
    'Home page' => '',
    'ID' => '',
    'Last Name' => '',
    'Latitude' => '',
    'Lesson Place' => '',
    'Login' => '',
    'Longitude' => '',
    'Map' => '',
    'Middle Name' => '',
    'My Account' => '',
    'My Adverts' => '',
    'Name' => '',
    'News' => '',
    'No advert prices filled' => '',
    'No experience' => '',
    'Phone' => '',
    'Place And Price' => '',
    'Promotions' => '',
    'Reset' => '',
    'Search' => '',
    'Study Place' => '',
    'StudyGoal' => '',
    'Subject' => '',
    'Subjects' => '',
    'Tutor Grade' => '',
    'TutorGrade' => '',
    'Tutorid' => '',
    'Tutors on map' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Years' => '',
    'remote' => '',
    'studentplace' => '',
    'tutorName' => '',
    'tutorplace' => '',
];
