<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Advanced Search' => 'Расширенный Поиск',
    'Advert' => 'Объявление',
    'AdvertAddress' => 'Адрес',
    'AdvertPrice' => 'Цена за 45 минут',
    'Advertid' => '',
    'Adverts' => '@@Объявления@@',
    'Any' => 'Не важно',
    'Are you sure you want to delete this item?' => '',
    'Avatar' => 'Аватар',
    'Cancel' => 'Отмена',
    'City' => 'Город',
    'Contact' => 'Контакты',
    'Create' => 'Создать',
    'Create Advert' => '@@Добавить объявление@@',
    'Create Subject' => 'Добавить Предмет',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit' => 'Редактировать',
    'Experience' => 'Стаж преподавания',
    'First Name' => 'Имя',
    'For Tutors' => 'Репетиторам',
    'Goal' => 'Цель',
    'Goals' => 'Цели',
    'Home page' => 'Главная',
    'ID' => '',
    'Last Name' => 'Фамилия',
    'Latitude' => '',
    'Lesson Place' => 'Место проведения',
    'Login' => 'Логин',
    'Longitude' => '',
    'Map' => 'Карта',
    'Middle Name' => 'Отчество',
    'My Account' => 'Аккаунт',
    'My Adverts' => 'Мои объявления',
    'Name' => 'Имя',
    'News' => 'Новости',
    'No advert prices filled' => 'Стоимость занятий не указана',
    'No experience' => 'Без опыта',
    'Phone' => 'Телефон',
    'Place And Price' => 'Цена и Место',
    'Promotions' => 'Акции',
    'Reset' => 'Сбросить',
    'Search' => 'Поиск',
    'Study Place' => 'Место проведения',
    'StudyGoal' => 'Цель занятий',
    'Subject' => 'Предмет',
    'Subjects' => 'Предметы',
    'Tutor Grade' => 'Статус репетитора',
    'TutorGrade' => 'Статус репетитора',
    'Tutorid' => '',
    'Tutors on map' => 'Репетиторы на карте',
    'Update' => 'Обновить',
    'Update {modelClass}: ' => '',
    'Years' => 'лет',
    'remote' => 'Дистанционно',
    'studentplace' => 'У ученика',
    'tutorName' => 'Имя Репетитора',
    'tutorplace' => 'У преподавателя',
];
